### ISSUE TITLE
share checkpoint in others way

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [PinataFarms/DAD-3DHeads#1]
great works!

Can you share checkpoint in others way? the model url is hard to download

**Comment by t-martyniuk** [comment]
Dear ZHANG-SHI-CHANG,

could you please elaborate what causes the troubles?

Also, we will consider providing another way the checkpoint is retrieved, stay tuned.

**Comment by burnmyletters** [comment]
Hello, 

we have shared the alternative link [here](https://github.com/PinataFarms/DAD-3DHeads/issues/3#issuecomment-1174886281)

**Comment by ypflll** [comment]
@burnmyletters @t-martyniuk  Hi, thank you for releasing the model. I found it's hard when I tried to integrate it in my network for training, because the released model is saved by torch.jit.save.
Can you release a version that is saved by torch.save?
Thanks very much!

**Comment by ypflll** [comment]
I found that state_dict can be exported from the released model, so I solved my issue.
