### ISSUE TITLE
How to align the test image to get correct result?

### ISSUE THREAD

**Issue by Seanseattle** [PinataFarms/DAD-3DHeads#10]
Thanks for your excellent work. I have one question about the image preprocessing. Does it have a standard alignment process (e.g. face detection) before sending the test image to the network? I got bad results when the input images have lots of background area.

**Comment by t-martyniuk** [comment]
thank you!

as it is mentioned in the paper, "Given an image, we assume the head is detected, loosely cropped, and approximately centered". We emphasise **head** here, as usual face detection algorithms do not necessarily capture the whole skull in the bounding box. We use a proprietary head detection model for that, but one can either use any open-source **head** detector, or train their own one.
