### ISSUE TITLE
about pose annotation

### ISSUE THREAD

**Issue by rlczddl** [PinataFarms/DAD-3DHeads#11]
how to get true yaw, pitch, roll  annotation from current dataset?

**Comment by littlePrince126** [comment]
It can be supervised by 3D landmarks.

**Comment by t-martyniuk** [comment]
Dear @rlczddl ,

we discuss in the paper why we prefer rotation matrices over RPY values (see Section 5.1). To get the former from our annotations, please see issue #13 (or have a look below), there is a conversion formula. We are also planning to release an updated version of the dataset with GT rotation matrix included for simplicity and usability.

The aforementioned formula: 

```
def get_gt_rot_mat(annotation):
    rot_180 = np.array([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    mv = rot_180 @ annotation.mesh.model_view_matrix
    R_gt = mv[:3, :3]
    return R_gt
```
Hope this helps!
