### ISSUE TITLE
Would you please add the head pose label for all head images?

### ISSUE THREAD

**Issue by hnuzhy** [PinataFarms/DAD-3DHeads#13]
Thank you very much for your excellent work and dataset for person face/head analysis. I found that the released DAD-3DHeads only contains dense 3D head mesh shape and two matrices. It does not give the head pose label of each head, such as Euler angles and rotation matrix. This makes it difficult to apply this dataset for head pose estimation task. But this dataset is obviously more comprehensive and challenging than BIWI and 300W-LP. It would be a huge pity if it could not be used to study head pose estimation. Hope you can build and release the DAD-3DHeads-V2 with at least head pose label~

**Comment by KupynOrest** [comment]
Thanks a lot for your comment, we will release an updated annotations with an alternative pose representation.
Meanwhile please use this code to compute the rotation matrix

`def get_gt_rot_mat(annotation):
    rot_180 = np.array([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    mv = rot_180 @ annotation.mesh.model_view_matrix
    R_gt = mv[:3, :3]
    return R_gt
`

**Comment by hnuzhy** [comment]
> Thanks a lot for your comment, we will release an updated annotations with an alternative pose representation. Meanwhile please use this code to compute the rotation matrix
> 
> ```
> def get_gt_rot_mat(annotation):
>     rot_180 = np.array([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
>     mv = rot_180 @ annotation.mesh.model_view_matrix
>     rotation_matrix = mv[:3, :3]
>     return rotation_matrix
> ```

That's great! Thank you for your advice and conversion code. :-) I will use it in my research.

**Comment by Ding2Zhen** [comment]
Thank you very much for your excellent work and dataset for person face/head analysis. The Euler angles I get using the rotation matrix are very different from the Euler angles in the predictions obtained in the demo.py, and I find that the predicted Euler angles look a little more accurate, but the Euler angles obtained by the rotation matrix are quite incorrect.
I would appreciate you being able to elaborate on how the Euler angle is calculated in the code, thank you very much.
