### ISSUE TITLE
FaceBuilder cannot export FLAME head model

### ISSUE THREAD

**Issue by littlePrince126** [PinataFarms/DAD-3DHeads#14]
I have attempted facebuilder with mid poly（4646 vertices）. But I cannot export 5023 vertices as FLAME topology .
Thanks a lot!

**Comment by t-martyniuk** [comment]
DAD-3DHeads is a dataset built with PiñataFarms proprietary annotation tool (that was indeed inspired by FaceBuilder), but the annotations do not come directly from either FaceBuilder or any other kind of publicly available software.

Thank you!
