### ISSUE TITLE
it is not so good, it is good only for the 1.jpeg image.

### ISSUE THREAD

**Issue by sunjunlishi** [PinataFarms/DAD-3DHeads#18]
![2_face_mesh](https://user-images.githubusercontent.com/11845664/201469418-049e9095-485f-49ca-8415-1df345ccbf24.png)
![220421idcardposNew_0](https://user-images.githubusercontent.com/11845664/201469426-9700b714-a9fb-4946-92ee-7268d161998e.jpg)
![1_445_landmarks](https://user-images.githubusercontent.com/11845664/201469431-54e60536-3816-4cfe-8a4e-9d3b65271f32.png)
need retraining?

**Comment by t-martyniuk** [comment]
It is sensitive to the way you crop the head, indeed. If you want to have the model work on your custom crops, you would likely need to retrain the model for your particular use case. The training code is available in the repo.

The training dataset contains bounding boxes for heads. You can see here https://github.com/PinataFarms/DAD-3DHeads/blob/bfb7371814d2d41fba6a472ebc5cc4c023dec5df/model_training/data/flame_dataset.py#L97-L98 how we pre-process those bounding boxes during the training stage.
