### ISSUE TITLE
Loss weight setting inconsistent with your config in paper

### ISSUE THREAD

**Issue by X-niper** [PinataFarms/DAD-3DHeads#23]
Hi, I find that the loss weight of smoothL1 in code is 100 but 1 in paper. I want to know which one is correct. 

Besides, you mention that your dataset has no augmentation but in the code, the bbox is offset randomly. I want to know whether you include this offset when the released model was trained. 

Thanks,

**Comment by t-martyniuk** [comment]
I believe that the version in the code configs should be the final one, thanks for pointing out the inconsistency.

Indeed, the offset is random, you're right. We included it in the released model training. As for other typical augmentations - either spatial- or pixel-level - we didn't use them in the released model.

Thanks for your interest.
