### ISSUE TITLE
dataset request form no reply

### ISSUE THREAD

**Issue by Michelle-mm** [PinataFarms/DAD-3DHeads#27]
hello, i've filled the google form twice for the dataset. yet I haven't gotten any reply.  do i need to fill it again?? thank you!

**Comment by t-martyniuk** [comment]
could you please leave your e-mail in the comments here? did you use academic e-mail?

**Comment by t-martyniuk** [comment]
I guess it should be resolved. In case the issue persists - please contact us directly via mail.

**Comment by Michelle-mm** [comment]
hello,
I sent this email in case you didn't see my reply. thank you!

葉思辰 ***@***.***> 於 2023年3月7日 週二 下午5:20寫道：
