### ISSUE TITLE
Can this model produce such dense grid model or mesh information?

### ISSUE THREAD

**Issue by momei123** [PinataFarms/DAD-3DHeads#28]
![banner](https://user-images.githubusercontent.com/30890794/225198297-0c02a31e-71c7-40ac-9ae6-526362cb39d5.png)

**Comment by t-martyniuk** [comment]
No, this model results in the mesh grid following FLAME topology. This image serves only as a visualization.

**Comment by momei123** [comment]
Thanks, 
    I've solved this mesh render problem with a combination of other algorithms!
