### ISSUE TITLE
Can I use labeling tools?

### ISSUE THREAD

**Issue by hyojk2001** [PinataFarms/DAD-3DHeads#31]
Thanks for your excellent services!

I want to build new face dataset consisted of 445 landmarks, but I don't know how to use this tools for dense landmarks.

Can I use them? If I can, how can I use labeling tool?

**Comment by t-martyniuk** [comment]
With DAD-3DHeads Dataset you can obtain 445 landmarks per image from the data that we released. 
As per labeling new data *with the same labeling tool* - the labeling tool that was used is proprietary, so this option is not available for the community.

You can use the results of DAD-3DNet as pseudolabels, though, - that's what I would recommend you to do.
