### ISSUE TITLE
ALFW2000-3D preprocessing

### ISSUE THREAD

**Issue by b0ku1** [PinataFarms/DAD-3DHeads#33]
Hi there, 

Could you please share how you preprocessed ALFW2000 images to your format? From the paper:
"Given an image, we assume the head is detected, loosely cropped, and approximately centered"

Thanks.

**Comment by t-martyniuk** [comment]
Hi,

we are planning on releasing the bounding boxes in the next update. Stay tuned! Thanks for your interest.
