### ISSUE TITLE
Error when calculating metrics

### ISSUE THREAD

**Issue by JuanjoFlores** [PinataFarms/DAD-3DHeads#35]
Hi, my problem is that when I benchmark, the metrics do not match the expected results for most of the images in the validation set. For example, for the whole validation set when comparing the predictions with the ground truth I get the following results: 
nme_reprojection: 41.0635
z5_accuracy: 0.820
pose_error: 0.82040

I don't know why this is happening, because if I draw the landmarks predicted by the model on the images, they are not so far away from the annotations.

**Comment by t-martyniuk** [comment]
Hello. 
Could you please elaborate? 

I can't really help without any details, but the problem can be in scaling or orientation (maybe, some of your XYZ-axis are facing wrong direction)?
