### ISSUE TITLE
dataset request form no reply :(

### ISSUE THREAD

**Issue by theamircodex** [PinataFarms/DAD-3DHeads#37]
Hello I'm interested in artificial intelligence face recognition and I'm high school student ,i've filled the google form for the dataset. I haven't gotten any reply yet . my email : amirshooter1453@gmail.com

**Comment by razvanab** [comment]
Same here.

**Comment by acmlau** [comment]
@razvanab @theamircodex I have requested today, and got a link straightaway. The is to use your institutional email to request is I think... And the first time I requested it, I didn't notice it sitting in my junk email, so maybe it's worth it to have a look there. Good luck :)

**Comment by t-martyniuk** [comment]
Hello.
Indeed, you have to use your institutional email (for example, of your research institution or university) to receive the download link.

**Comment by ImistroI** [comment]
Hello, 
I am also interested for the dataset for my bachelor thesis and I used my institutional email but still got no reply.
Thanks in advance.

**Comment by t-martyniuk** [comment]
> Hello, I am also interested for the dataset for my bachelor thesis and I used my institutional email but still got no reply. Thanks in advance.

could you please let me know via email what was the email you requested it from? or at least the institution domain. I will double-check.

**Comment by ImistroI** [comment]
> > Hello, I am also interested for the dataset for my bachelor thesis and I used my institutional email but still got no reply. Thanks in advance.
> 
> could you please let me know via email what was the email you requested it from? or at least the institution domain. I will double-check.

the email was from the university of stuttgart

**Comment by ImistroI** [comment]
> > Hello, I am also interested for the dataset for my bachelor thesis and I used my institutional email but still got no reply. Thanks in advance.
> 
> could you please let me know via email what was the email you requested it from? or at least the institution domain. I will double-check.

the email was from the university of stuttgart with the domain @stud.uni-stuttgart.de

**Comment by t-martyniuk** [comment]
> > > Hello, I am also interested for the dataset for my bachelor thesis and I used my institutional email but still got no reply. Thanks in advance.
> > 
> > 
> > could you please let me know via email what was the email you requested it from? or at least the institution domain. I will double-check.
> 
> the email was from the university of stuttgart with the domain @stud.uni-stuttgart.de

that is weird as i don't see it in our logs.
could you please write an email to `dad3dheads@gmail.com` from that email, and we'll proceed from there?
