### ISSUE TITLE
Metadata val.json missing attributes labels

### ISSUE THREAD

**Issue by acmlau** [PinataFarms/DAD-3DHeads#38]
You mention on the [README](https://github.com/PinataFarms/DAD-3DHeads#:~:text=Metadata%20%5Btrain%7Cval%7Ctest%5D.json%20file%20structure%3A) that the metafiles are all structured the same. However, the val.json does not contain the attributes for the items. I though I had a corrupted file and redownloaded the dataset zip file, but it is still missing in the new download as well. 

Are those attributes for the validation subset available for public? 

Hope to hear from you soon.

**Comment by t-martyniuk** [comment]
Thank you for your interest.

No, unfortunately, only training and test subsets have the attribute information available.
