### ISSUE TITLE
Request for Assistance with Error in Code - ValueError: Unexpected keyword arguments: `compute_on_step`

### ISSUE THREAD

**Issue by ImistroI** [PinataFarms/DAD-3DHeads#39]
Hello together,

After getting the dataset I want to try to run the train.py file but after running the code I get this error: 

Error executing job with overrides: []
Traceback (most recent call last):
  File "train.py", line 44, in run_experiment
    train(config)
  File "train.py", line 22, in train
    dad3d_net = FlameLightningModel(model=model, config=config, train=train_dataset, val=val_dataset)
  File "/homes/jonas/DAD-3DHeads/model_training/train/flame_lightning_model.py", line 72, in __init__
    self.iou_metric = SoftIoUMetric(compute_on_step=True)
  File "/homes/jonas/DAD-3DHeads/model_training/metrics/iou.py", line 44, in __init__
    super().__init__(
  File "/projects/envs/conda/jonas/envs/py3.8_new/lib/python3.8/site-packages/torchmetrics/metric.py", line 146, in __init__
    raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")
ValueError: Unexpected keyword arguments: `compute_on_step`

these are my packages on my machine:
absl-py==2.0.0
aiohttp==3.8.6
aiosignal==1.3.1
albumentations==1.0.0
antlr4-python3-runtime==4.8
async-timeout==4.0.3
attrs==23.1.0
cachetools==5.3.2
certifi==2023.7.22
charset-normalizer==3.3.2
chumpy==0.70
coloredlogs==15.0.1
fire==0.5.0
frozenlist==1.4.0
fsspec==2023.10.0
google-auth==2.23.4
google-auth-oauthlib==1.0.0
grpcio==1.59.2
humanfriendly==10.0
hydra-core==1.1.0
idna==3.4
imageio==2.32.0
importlib-metadata==6.8.0
importlib-resources==6.1.1
joblib==1.3.2
lazy_loader==0.3
lightning-utilities==0.9.0
Markdown==3.5.1
MarkupSafe==2.1.3
multidict==6.0.4
networkx==3.1
numpy==1.22.0
oauthlib==3.2.2
omegaconf==2.1.2
opencv-python==4.8.1.78
opencv-python-headless==4.8.1.78
packaging==23.2
Pillow==10.0.1
protobuf==4.25.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pyDeprecate==0.3.2
pytorch-lightning==1.6.0
pytorch-ranger==0.1.1
pytorch-toolbelt==0.5.0
pytorchcv==0.0.65
PyWavelets==1.4.1
PyYAML==6.0.1
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
scikit-image==0.21.0
scikit-learn==1.3.2
scipy==1.10.1
six==1.16.0
smplx==0.1.26
tensorboard==2.14.0
tensorboard-data-server==0.7.2
termcolor==2.3.0
threadpoolctl==3.2.0
tifffile==2023.7.10
timm==0.4.5
torch==1.9.0
torch-optimizer==0.1.0
torchgeometry==0.1.2
torchmetrics==1.2.0
torchvision==0.10.0
tqdm==4.66.1
typing_extensions==4.8.0
urllib3==2.0.7
Werkzeug==3.0.1
yarl==1.9.2
zipp==3.17.0

I also tried on different devices but still go the same result above.

thanks in advance

**Comment by khamneeda** [comment]
Hello:)

I'm struggling with the same problem. 
If you resolved this, can you share your approach?

Thank you in advance.
