### ISSUE TITLE
It seems that training with Multi-GPUs will result inferior results.

### ISSUE THREAD

**Issue by hnuzhy** [PinataFarms/DAD-3DHeads#40]
Hello, Tetiana. I'm recently retraining the original project. Different from your implementation in the paper running with **1 RTX A6000**, I  retrained DAD-3DNet with **3 RTX 3090**, but got inferior results with training at least 100 epochs. The batchsize on each GPU is 96. Thus, the total batchsize is 288, which is similar with your given batchsize 256.

Belows are my evaluation results on the DAD-3DHeads `val-set`.
* Your results (using the released model weight): `{'nme_reprojection': 1.9804347670962774, 'z5_accuracy': 0.9569228042646247, 'chamfer': 2.7485585, 'pose_error': 0.12988624173861432}`
* My results: `{'nme_reprojection': 2.2882715349235956, 'z5_accuracy': 0.9563515915670164, 'chamfer': 2.8907034, 'pose_error': 0.13523285796228382}`

Am I missing some important details? Or is it because of inconsistencies in multi-card training? Looking forward to your reply.

**Comment by t-martyniuk** [comment]
Hello, @hnuzhy. 

We did not run any carefully designed ablation on the batch size, so I can't really give you any insights into that, but in the development process we indeed noticed that sticking to the hyper parameters we chose lead to superior results.

**Comment by hnuzhy** [comment]
> Hello, @hnuzhy.
> 
> We did not run any carefully designed ablation on the batch size, so I can't really give you any insights into that, but in the development process we indeed noticed that sticking to the hyper parameters we chose lead to superior results.

OK. I just need your original results of DAD-3DNet as the baseline. The reason for my inferior implementation results seems to be inconsistent hyper parameters with yours. Whatever, I will take your reported results for comparing. Thank you for your reply.
