### ISSUE TITLE
3d meshes are upside down

### ISSUE THREAD

**Issue by JonasNasimzada** [PinataFarms/DAD-3DHeads#41]
Hello,

after experimenting with the repo I attract attention the the generating 3d meshes are upside down. The landmarks and the head mesh seems quite right but the 3d obj mesh are always upside down and are little bit tilted is this intended or did I do a mistake? 

![1_445_landmarks](https://github.com/PinataFarms/DAD-3DHeads/assets/150592182/3ce4daf5-6f7b-4d14-abb2-a16ca0a67fb5)
![1_head_mesh](https://github.com/PinataFarms/DAD-3DHeads/assets/150592182/2c44b18b-024f-4985-b86e-de7f1c9b877c)
![Screenshot 2023-11-30 at 12 18 45](https://github.com/PinataFarms/DAD-3DHeads/assets/150592182/783a85c7-0a62-4756-bb8c-9a94c05bf28b)

**Comment by annamariapalese** [comment]
I have the same issue, did you fix it?

**Comment by t-martyniuk** [comment]
Dear all,

it's not "intended", but we also didn't specifically aim at having them oriented in such axes configuration that when loaded to Blender it would be upright. You can easily add a minor post-processing that would rotate the output mesh the way you want. In general, our 3D mesh output is focused on the shape+expression of the head, not on the position in space.
