### ISSUE TITLE
Rotation Matrix

### ISSUE THREAD

**Issue by THARUNESHWAR-369** [PinataFarms/DAD-3DHeads#44]
```
"rotation": [
    1.8011109828948975,
    -0.24679288268089294,
    -0.46465161442756653,
    -0.025814266875386238,
    -1.6643542051315308,
    -0.025605857372283936
  ],
  "translation": [1.9939076900482178, 3.443227767944336, 0.0],
  "scale": [23.91216468811035],
  "jaw": [0.05481124296784401, -0.006581000052392483, -0.0004232260398566723],
```

@burnmyletters @KupynOrest @t-martyniuk @NeelayS are any one can you explain the why rotation has 6 values.

**Comment by t-martyniuk** [comment]
Hi, @THARUNESHWAR-369 !

Sure, you can see in the paper, Section 4.2, "Shape+Expression Loss", where we argue 

> The global rotation pose is modeled by $\overrightarrow{\theta_{r}}\in\mathbb{R}^{6}$ for continuity of representation [1], and is separated from the jaw rotation pose vector $\overrightarrow{\theta_{j}}\in\mathbb{R}^{3}$. 

You can see the transformation from the 6 parameters to the rotation matrix here: https://github.com/PinataFarms/DAD-3DHeads/blob/3acc5c2a1177d354a1247c49e44a83ad682ea6a1/model_training/model/utils.py#L92

Hope this helps.

[1] Zhou, Yi, et al. "On the continuity of rotation representations in neural networks." Proceedings of the IEEE/CVF conference on computer vision and pattern recognition. 2019.

**Comment by THARUNESHWAR-369** [comment]
@t-martyniuk  Thank you
