### ISSUE TITLE
How do I build the custom training dataset?

### ISSUE THREAD

**Issue by hewumars** [PinataFarms/DAD-3DHeads#5]
How do I build the custom training dataset? I use FaceBuilder for blender to annotate images,but I don't know how to generate the label json file.

**Comment by leifengsoul** [comment]
I have the same problem, who can help me?

**Comment by t-martyniuk** [comment]
Thanks for your interest in the dataset!

DAD-3DHeads is a dataset built with PiñataFarms proprietary annotation tool (that was indeed inspired by FaceBuilder), but the annotations do not come directly from either FaceBuilder or any other kind of publicly available software. That said, we cannot advise you upon label json file generation, as the aforementioned custom annotation tool is not intended to be part of the project release.
